# Generated by Django 4.2.14 on 2024-07-19 15:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
